### ISSUE TITLE
document is not valid

### ISSUE THREAD

**Issue by ashish-joshi-sr** [alexfraundorf-com/ship#9] opened 2015-09-08 10:29 UTC
i tried to get response from the API you have developed, but when i try to run get_rates_example.php

it shows following error:
Error: UPS SOAP Request failed - An exception has been raised as a result of client data. - Serialized Details: O:8:"stdClass":2:{s:8:"Severity";s:4:"Hard";s:16:"PrimaryErrorCode";O:8:"stdClass":2:{s:4:"Code";s:5:"10002";s:11:"Description";s:61:"The XML document is well formed but the document is not valid";}}

**Comment by alexfraundorf-com** [comment] 2015-09-08 17:57
This appears to be something wrong with your request or credentials, not a
bug in the library.  Please email me a copy of your xml request.  I will
take a look at it and see if I can see what is wrong with it.  If you do
not have my email address, please contact me through AlexFraundorf.com and
request it.  Thanks.

Alex Fraundorf
AlexFraundorf.com
SnapProgramming.com

**Comment by alexfraundorf-com** [comment] 2015-09-11 14:22
User data issue, not a bug.  Closing issue.

**Closed as completed by alexfraundorf-com** 2015-09-11 14:22 UTC
